# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: data

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */12 * * *"
  push:
    paths:
      - "data.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: clear
        run: |
          git filter-branch --force --index-filter "git rm -rf --cached --ignore-unmatch class zdata zlog t.json z.json" --prune-empty --tag-name-filter cat -- --all

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run main.py
        run: |

          python main.py

      - name: Commit files
        run: |
          git config --local user.email "ruytzzzgo@gmail.com"
          git config --local user.name "RuytzzZ"
          git add *
          git commit -m "push"
          git push --force
 
